autoload -Uz compinit
compinit
export PATH="$HOME/.composer/vendor/bin:$PATH"
export PATH="/opt/homebrew/sbin:$PATH"
export PATH=/opt/homebrew/bin:$PATH
export PATH="/usr/local/sbin:$PATH"
export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools
export PS1="%1d %# "
alias npass="python3 /Users/andersiglebekk/Documents/Apps/PasswordGenerator/passwordgenerator.py"
alias pa="php artisan"
alias lpint="./vendor/bin/pint"
alias c="composer"
alias gaa="git add --all"
alias gcm="git commit -m"
alias gp="git push"
alias wip='gaa && gcm "wip" && gp'
alias phpunit="vendor/bin/phpunit"
alias pu="vendor/bin/phpunit"
alias puw="phpunit-watcher watch --testdox"
alias stan="vendor/bin/phpstan"
alias dos="doctl serverless"
alias caf="caffeinate"
alias sail='[ -f sail ] && sh sail || sh vendor/bin/sail'
alias gogogo="git pull && valet open && code . && npm install && npm run dev"
export PATH="/opt/homebrew/opt/openjdk@17/bin:$PATH"
